{
    "name": "Restaurant Waitlist",
    "version": "19.0.1.0.0",
    "summary": "Waitlist management for Odoo Restaurant.",
    "description": "Adds a functional restaurant waitlist connected to PoS Restaurant tables.",
    "author": "Augusto",
    "license": "LGPL-3",
    "category": "Point of Sale",
    "depends": ["base", "contacts", "point_of_sale", "pos_restaurant"],
    "data": [
        "security/ir.model.access.csv",
        "data/admin_user.xml",
        "data/sequence.xml",
        "data/restaurant_demo_data.xml",
        "views/restaurant_waitlist_views.xml",
        "views/menus.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
